sudo: required
services:
  - docker
  before_install:
    - docker build -t akinmano/docker-react -f Dockerfile.dev .

    script:
      - docker run akkinmano/docker-react npm run test -- -- coverage
